name: ci
on:
  push:
    branches:
      - '**'
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - PubSub_pro8MHzatmega328
          - ConnectEthernetClient_pro8MHzatmega328
          - ConnectEsp8266WiFiClient_esp12e
          - LwtEsp8266WiFiClient_esp12e
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install platformio
      - name: Build
        run: pio run -e $TARGET
        env:
          TARGET: ${{ matrix.target }}
